// ! non toccare questo file perche e autogenerato con firebase-secrets-cli

import { defineSecret } from 'firebase-functions/params';

export const secret = {
    GEMINI_API_KEY: 'GEMINI_API_KEY',
    GOOGLE_SERVICE_ACCOUNT_EMAIL: 'GOOGLE_SERVICE_ACCOUNT_EMAIL',
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: 'GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY',
    HUBCORTEX_API_KEY: 'HUBCORTEX_API_KEY',
    WHATSAPP_BUSINESS_ACCESS_TOKEN: 'WHATSAPP_BUSINESS_ACCESS_TOKEN',
    WHATSAPP_BUSINESS_PHONE_NUMBER_ID: 'WHATSAPP_BUSINESS_PHONE_NUMBER_ID',
    WHATSAPP_WEBHOOK_VERIFY_TOKEN: 'WHATSAPP_WEBHOOK_VERIFY_TOKEN',
} as const;

export const GEMINI_API_KEY = defineSecret('GEMINI_API_KEY');
export const GOOGLE_SERVICE_ACCOUNT_EMAIL = defineSecret('GOOGLE_SERVICE_ACCOUNT_EMAIL');
export const GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY = defineSecret('GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY');
export const HUBCORTEX_API_KEY = defineSecret('HUBCORTEX_API_KEY');
export const WHATSAPP_BUSINESS_ACCESS_TOKEN = defineSecret('WHATSAPP_BUSINESS_ACCESS_TOKEN');
export const WHATSAPP_BUSINESS_PHONE_NUMBER_ID = defineSecret('WHATSAPP_BUSINESS_PHONE_NUMBER_ID');
export const WHATSAPP_WEBHOOK_VERIFY_TOKEN = defineSecret('WHATSAPP_WEBHOOK_VERIFY_TOKEN');
